// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ci8t2Tfbn4l0YoFy0Em_8hwoWFGzlIA',
    appId: '1:459739357836:web:004018883a36634b7791a9',
    messagingSenderId: '459739357836',
    projectId: 'octaklinik',
    authDomain: 'octaklinik.firebaseapp.com',
    storageBucket: 'octaklinik.firebasestorage.app',
    measurementId: 'G-7WMK5DPW1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQZjEcmSU2DaBsb8aB5xC7TNKgZ5iI2A',
    appId: '1:459739357836:android:9cb037fe055dff3f7791a9',
    messagingSenderId: '459739357836',
    projectId: 'octaklinik',
    storageBucket: 'octaklinik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDLPk-ms6RW7Ewq2DrxH13xGsS0mkjq0',
    appId: '1:459739357836:ios:b877b9564a5a4dec7791a9',
    messagingSenderId: '459739357836',
    projectId: 'octaklinik',
    storageBucket: 'octaklinik.firebasestorage.app',
    iosBundleId: 'com.example.appOctaklinik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhDLPk-ms6RW7Ewq2DrxH13xGsS0mkjq0',
    appId: '1:459739357836:ios:b877b9564a5a4dec7791a9',
    messagingSenderId: '459739357836',
    projectId: 'octaklinik',
    storageBucket: 'octaklinik.firebasestorage.app',
    iosBundleId: 'com.example.appOctaklinik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ci8t2Tfbn4l0YoFy0Em_8hwoWFGzlIA',
    appId: '1:459739357836:web:7bf2df438e5c78cc7791a9',
    messagingSenderId: '459739357836',
    projectId: 'octaklinik',
    authDomain: 'octaklinik.firebaseapp.com',
    storageBucket: 'octaklinik.firebasestorage.app',
    measurementId: 'G-XPFH6085RB',
  );
}
